### ISSUE TITLE
feature request: support builtin sourcemap

### ISSUE THREAD

**Issue by undefined-moe** [rarecoil/unwebpack-sourcemap#24]
like this:

foo.js

```js
xxxxxx
//# sourceMappingURL=data:application/json;charset=utf-8;base64,xxxxxx
```

**Comment by psociety** [comment]
@undefined-moe if you're in a hurry, you can always manually b64 decode the mapping (it then will be a normal sourceMapping), save it as "source.map" and point unwebpack against it.

**Comment by rarecoil** [comment]
Feel free to issue a PR for it and I'll try to get around to reviewing it.
