### ISSUE TITLE
ERROR: Failed to parse sourcemap  

### ISSUE THREAD

**Issue by tahamarzak20** [rarecoil/unwebpack-sourcemap#27]
when i use the script i always get the error : 
ERROR: Failed to parse sourcemap  
 InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn((
i put the url.map 
i dont know where is the prob

**Comment by rarecoil** [comment]
Please try the current script on master. It appears there were a few bugs worked out by other contributors.
