### ISSUE TITLE
Passthrough is not supported, GL is disabled

### ISSUE THREAD

**Issue by dashingsuma** [rarecoil/unwebpack-sourcemap#29]
![image](https://user-images.githubusercontent.com/10601986/155855216-7dd3378e-a2bf-4b61-9e6e-20d7e036ec73.png)

**Comment by giacomoferretti** [comment]
Can you give us more information to help us reproduce this error?
Like OS (I know it's Windows based on the screenshot, but include it next time 😉), command ran, script's version, expected behaviour, etc...

**Comment by rarecoil** [comment]
Nothing in this script should be giving you the output that you have above. This looks like something you'd expect to see from Chrome or a headless browser (e.g. puppeteer) which are not used by this. Please reopen if you have more information.
